#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>

#define PADRAO "ola mundo, este eh um teste de meltdown pra materia do brafman"
#define PAGES 700000




int main(int argc, char ** argv)
{
	char *src="OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"


	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"


	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	"OLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANOLA MUNDO ESSE EH UM TESTE PARA AMATERIADO BRAFMANAAAAAAAAAAAAAAAAAAAAAAAAAA";


	char* diretorio[PAGES];
	size_t i,j;
	char *buffer;
	size_t len=strlen(src)+1;
	printf("tamanhdo da string= %u\n",len);
	j=0;
	printf("tamanho de i=%u\n",i);	
	//sleep(70000);
	

	while (i <PAGES)
	{
		
		buffer=malloc(4096);
		if(buffer!=NULL)
		{
		  diretorio[i]=buffer;
		  strcpy(buffer,src);
		
		  i++;
	      	  if(i%100==0)
		  {
		    printf("usando %u paginas\n",i);			
		  }
		}
	
	
	}
	sleep(60000);
	return 0;

}
